### PR TITLE
Update to current login and upload API

### PR DESCRIPTION
**Pull request by kinkie**
Current MediaWiki API requires an InternWiki to be supplied to the login request,
and the API endpoint to collect an authentication token has changed.

This has been tested by converting the Squid Web Cache wiki

### CODE REVIEW

**Comment by rufuspollock** [comment]
@kinkie thanks!

**Comment by rufuspollock** [comment]
@amercader could you merge this?

**Comment by sidrew** [comment]
Was this ever merged? @rufuspollock @amercader

**Comment by amercader** [comment]
@sidrew no, it was not merged. I will push the button but I have not enough knowledge to judge if it is a reasonable change. If someone with more experience wants to step up and help maintain this repo I'll be happy to give them access rights.

**Pull request merged**
